import os
from pathlib import Path

BASE_DIR = Path(__file__).resolve().parent.parent
WEIGHTS_PATH = os.getenv("MODEL_WEIGHTS", str(
    BASE_DIR / "weights" / "best.pt"))

ALL_CLASSES = [
    "HEALTHY",
    "NITROGEN_DEFICIENCY",
    "PHOSPHORUS_DEFICIENCY",
    "POTASSIUM_DEFICIENCY",
    "CALCIUM_DEFICIENCY",
    "MAGNESIUM_DEFICIENCY",
]

RAW_CLASS_MAP = {
    "CA_DEFICIENCY": "CALCIUM_DEFICIENCY",
    "K_DEFICIENCY": "POTASSIUM_DEFICIENCY",
    "MG_DEFICIENCY": "MAGNESIUM_DEFICIENCY",
    "N_DEFICIENCY": "NITROGEN_DEFICIENCY",
    "P_DEFICIENCY": "PHOSPHORUS_DEFICIENCY",
    "FE_DEFICIENCY": "IRON_DEFICIENCY",
    "FULL_NUTRIENT": "HEALTHY",
    "FN": "HEALTHY",
    "HEALTHY": "HEALTHY",
}

MIN_CANOPY_COVERAGE_RATIO = 0.08
INFERENCE_IMAGE_SIZE = 224
CONFIDENCE_FLOOR = 0.50
AMBIGUITY_DELTA = 0.12
